services:
  goTogether-api:
    container_name: goTogether-api
    restart: always
    image: node:20.19.5
    ports:
      - 4003:3007
      - 3009:3009
    volumes:
      - ./:/usr/src/goTogether
    working_dir: /usr/src/goTogether
    env_file:
      - .env
    depends_on:
      - goTogether-mqtt
    networks:
      - monorepo-network
    command: sh -c "npm install && npm run build && npm run start:prod"

  goTogether-batch:
    container_name: goTogether-batch
    restart: unless-stopped
    image: node:20.19.5
    ports:
      - 4004:3008
    volumes:
      - ./:/usr/src/goTogether
    working_dir: /usr/src/goTogether
    env_file:
      - .env
    depends_on:
      - goTogether-mqtt
    networks:
      - monorepo-network
    command: sh -c "npm install && npm run build:batch && npm run start:prod:batch"

  goTogether-mqtt:
    image: eclipse-mosquitto:2
    container_name: goTogether-mqtt
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge
